//! REAL→TEXT parity against the REAL SQLite 3.53.4.
//!
//! The fixture (`tests/fixtures/fptext_353_golden.txt`, one
//! `<hex-bits> <rendered>` pair per line) was generated by linking the
//! official 3.53.4 amalgamation and calling `sqlite3_snprintf("%!.17g")`
//! — the exact machinery the VDBE's `vdbeMemRenderNum` uses for
//! REAL→TEXT (the `%!.*g` format at `db->nFpDigit = 17`). The case mix is
//! deterministic: hand-picked edges (±0, subnormals, 1-ulp neighbors of
//! every power of ten in range, ±inf, nan), parsed decimal literals, and
//! two LCG streams of raw bit patterns (full-range and exponent-clamped).
//!
//! SQLite 3.48 replaced the older `%!.15g` conversion with this
//! 17-significant-digit pipeline that also SHRINKS the digit count when a
//! shorter rendering round-trips (see `src/types/fptext.rs`). This test
//! pins the port byte-for-byte across 8481 doubles.

use rustqlite::types::fptext::render_real_353;

#[test]
fn real_to_text_matches_sqlite_353_byte_for_byte() {
    let data = include_str!("fixtures/fptext_353_golden.txt");
    let mut checked = 0usize;
    let mut mismatches = Vec::new();
    for line in data.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let (hex, want) = line
            .split_once(' ')
            .unwrap_or_else(|| panic!("malformed fixture line: {:?}", line));
        let bits = u64::from_str_radix(hex, 16).expect("hex bits");
        let v = f64::from_bits(bits);
        let got = render_real_353(v);
        if got != want {
            mismatches.push(format!("bits {hex}: got {got:?}, want {want:?}"));
        }
        checked += 1;
    }
    assert!(checked > 8000, "fixture too small: {checked} cases");
    assert!(
        mismatches.is_empty(),
        "{} of {} cases diverge:\n{}",
        mismatches.len(),
        checked,
        mismatches
            .iter()
            .take(12)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// The SQL surface routes through the same renderer: CAST AS TEXT,
/// string concatenation, and quote() must agree with the fixture.
#[test]
fn cast_concat_quote_use_the_parity_renderer() {
    let cases: &[(f64, &str)] = &[
        (1e300, "1.0e+300"),
        (2.0 / 3.0, "0.66666666666666663"),
        (1e16, "10000000000000000.0"),
        (1e17, "1.0e+17"),
        (49.47, "49.47"),
        (4.9e-324, "4.9406564584124654e-324"),
    ];
    let mut db = rustqlite::Database::open_in_memory().unwrap();
    db.execute("CREATE TABLE t(x REAL)", []).unwrap();
    for (v, want) in cases {
        db.execute("DELETE FROM t", []).unwrap();
        db.execute("INSERT INTO t VALUES (?)", [rustqlite::Value::Real(*v)])
            .unwrap();
        let rows = db
            .query("SELECT CAST(x AS TEXT), '' || x, quote(x), x FROM t", [])
            .unwrap();
        assert_eq!(rows.len(), 1, "one row");
        for (i, got) in rows[0].iter().take(3).enumerate() {
            let label = ["CAST", "||", "quote()"][i];
            assert_eq!(got.as_text(), *want, "{label} of {v}");
        }
        // And the raw value still round-trips bit-exactly.
        assert_eq!(rows[0][3].as_real(), *v, "raw value");
    }
}
