//! SQLite's exact double→text machinery, ported line-for-line from the
//! 3.53.4 amalgamation (`sqlite3FpDecode` / `sqlite3Fp2Convert10` /
//! `sqlite3Fp10Convert2` / the `%!.17g` etGENERIC assembly in
//! `sqlite3_str_vappendf`).
//!
//! Why: SQLite 3.48 replaced the old `%!.15g` REAL→TEXT conversion with a
//! high-precision binary↔decimal pipeline whose 17-digit default
//! (`db->nFpDigit`) additionally SHRINKS the digit count whenever a
//! shorter rendering round-trips back to the same double (the
//! `iRound==17` reduction in `sqlite3FpDecode` — `1e300` renders as
//! `1.0e+300`, not `1.0000000000000001e+300`; `49.47` renders as
//! `49.47`, not `49.469999999999999`). The reference C (including the
//! `aBase` / `aScale` / `aScaleLo` constant tables generated by SQLite's
//! own `tool/mkfptab.c --round`) is copied verbatim; the test suite
//! pins the port byte-for-byte against the real 3.53.4 library across a
//! randomized-double grid (tests/float_text_parity.rs).

// ---------------------------------------------------------------------------
// Constant tables (exact copies; generated by SQLite tool/mkfptab.c)
// ---------------------------------------------------------------------------

/// `aBase[p]` = the most significant 64 bits of `10^p` for p in 0..=26.
const A_BASE: [u64; 27] = [
    0x8000000000000000, //  0: 1.0e+0 << 63
    0xa000000000000000, //  1: 1.0e+1 << 60
    0xc800000000000000, //  2: 1.0e+2 << 57
    0xfa00000000000000, //  3: 1.0e+3 << 54
    0x9c40000000000000, //  4: 1.0e+4 << 50
    0xc350000000000000, //  5: 1.0e+5 << 47
    0xf424000000000000, //  6: 1.0e+6 << 44
    0x9896800000000000, //  7: 1.0e+7 << 40
    0xbebc200000000000, //  8: 1.0e+8 << 37
    0xee6b280000000000, //  9: 1.0e+9 << 34
    0x9502f90000000000, // 10: 1.0e+10 << 30
    0xba43b74000000000, // 11: 1.0e+11 << 27
    0xe8d4a51000000000, // 12: 1.0e+12 << 24
    0x9184e72a00000000, // 13: 1.0e+13 << 20
    0xb5e620f480000000, // 14: 1.0e+14 << 17
    0xe35fa931a0000000, // 15: 1.0e+15 << 14
    0x8e1bc9bf04000000, // 16: 1.0e+16 << 10
    0xb1a2bc2ec5000000, // 17: 1.0e+17 << 7
    0xde0b6b3a76400000, // 18: 1.0e+18 << 4
    0x8ac7230489e80000, // 19: 1.0e+19 >> 0
    0xad78ebc5ac620000, // 20: 1.0e+20 >> 3
    0xd8d726b7177a8000, // 21: 1.0e+21 >> 6
    0x878678326eac9000, // 22: 1.0e+22 >> 10
    0xa968163f0a57b400, // 23: 1.0e+23 >> 13
    0xd3c21bcecceda100, // 24: 1.0e+24 >> 16
    0x84595161401484a0, // 25: 1.0e+25 >> 20
    0xa56fa5b99019a5c8, // 26: 1.0e+26 >> 23
];

/// `aScale[g]` = the high 64 bits of `10^(27*(g-13))` (index 13 is the
/// special `1.0e-1 << 67` entry used for p == -1).
const A_SCALE: [u64; 26] = [
    0x8049a4ac0c5811ae, //  0: 1.0e-351 << 1229
    0xcf42894a5dce35ea, //  1: 1.0e-324 << 1140
    0xa76c582338ed2621, //  2: 1.0e-297 << 1050
    0x873e4f75e2224e68, //  3: 1.0e-270 << 960
    0xda7f5bf590966848, //  4: 1.0e-243 << 871
    0xb080392cc4349dec, //  5: 1.0e-216 << 781
    0x8e938662882af53e, //  6: 1.0e-189 << 691
    0xe65829b3046b0afa, //  7: 1.0e-162 << 602
    0xba121a4650e4ddeb, //  8: 1.0e-135 << 512
    0x964e858c91ba2655, //  9: 1.0e-108 << 422
    0xf2d56790ab41c2a2, // 10: 1.0e-81 << 333
    0xc428d05aa4751e4c, // 11: 1.0e-54 << 243
    0x9e74d1b791e07e48, // 12: 1.0e-27 << 153
    0xcccccccccccccccc, // 13: 1.0e-1 << 67 (special case)
    0xcecb8f27f4200f3a, // 14: 1.0e+27 >> 26
    0xa70c3c40a64e6c51, // 15: 1.0e+54 >> 116
    0x86f0ac99b4e8dafd, // 16: 1.0e+81 >> 206
    0xda01ee641a708de9, // 17: 1.0e+108 >> 295
    0xb01ae745b101e9e4, // 18: 1.0e+135 >> 385
    0x8e41ade9fbebc27d, // 19: 1.0e+162 >> 475
    0xe5d3ef282a242e81, // 20: 1.0e+189 >> 564
    0xb9a74a0637ce2ee1, // 21: 1.0e+216 >> 654
    0x95f83d0a1fb69cd9, // 22: 1.0e+243 >> 744
    0xf24a01a73cf2dccf, // 23: 1.0e+270 >> 833
    0xc3b8358109e84f07, // 24: 1.0e+297 >> 923
    0x9e19db92b4e31ba9, // 25: 1.0e+324 >> 1013
];

/// The next 32 significant bits after each `A_SCALE` entry.
const A_SCALE_LO: [u32; 26] = [
    0x205b896d, //  0: 1.0e-351 << 1229
    0x52064cad, //  1: 1.0e-324 << 1140
    0xaf2af2b8, //  2: 1.0e-297 << 1050
    0x5a7744a7, //  3: 1.0e-270 << 960
    0xaf39a475, //  4: 1.0e-243 << 871
    0xbd8d794e, //  5: 1.0e-216 << 781
    0x547eb47b, //  6: 1.0e-189 << 691
    0x0cb4a5a3, //  7: 1.0e-162 << 602
    0x92f34d62, //  8: 1.0e-135 << 512
    0x3a6a07f9, //  9: 1.0e-108 << 422
    0xfae27299, // 10: 1.0e-81 << 333
    0xaa97e14c, // 11: 1.0e-54 << 243
    0x775ea265, // 12: 1.0e-27 << 153
    0xcccccccc, // 13: 1.0e-1 << 67 (special case)
    0x00000000, // 14: 1.0e+27 >> 26
    0x999090b6, // 15: 1.0e+54 >> 116
    0x69a028bb, // 16: 1.0e+81 >> 206
    0xe80e6f48, // 17: 1.0e+108 >> 295
    0x5ec05dd0, // 18: 1.0e+135 >> 385
    0x14588f14, // 19: 1.0e+162 >> 475
    0x8f1668c9, // 20: 1.0e+189 >> 564
    0x6d953e2c, // 21: 1.0e+216 >> 654
    0x4abdaf10, // 22: 1.0e+243 >> 744
    0xbc633b39, // 23: 1.0e+270 >> 833
    0x0a862f81, // 24: 1.0e+297 >> 923
    0x6c07a2c2, // 25: 1.0e+324 >> 1013
];

/// Range of powers of 10 the tables cover.
const POWERSOF10_FIRST: i32 = -348;
const POWERSOF10_LAST: i32 = 347;

#[inline]
fn u64_bit(n: u32) -> u64 {
    1u64 << n
}

/// `pow10to2(p)` computes `floor(log2(pow(10,p)))` — arithmetic shifts,
/// matching C's `>>` on signed ints exactly.
#[inline]
fn pwr10to2(p: i32) -> i32 {
    (p * 108853) >> 15
}

/// `pow2to10(y)` computes `floor(log10(pow(2,y)))`.
#[inline]
fn pwr2to10(p: i32) -> i32 {
    (p * 78913) >> 18
}

/// Two inputs multiplied to a 128-bit result: `(high, low)`.
#[inline]
fn mul128(a: u64, b: u64) -> (u64, u64) {
    let r = (a as u128) * (b as u128);
    ((r >> 64) as u64, r as u64)
}

/// A = (a<<32)+aLo (96 bits), B = 64 bits. Returns the upper 64 bits of
/// the 160-bit product and the middle 32 bits (bits 64..96); the low 64
/// bits are discarded. (`sqlite3Multiply160`.)
#[inline]
fn mul160(a: u64, a_lo: u32, b: u64) -> (u64, u32) {
    let mut r = (a as u128) * (b as u128);
    r += ((a_lo as u128) * (b as u128)) >> 32;
    let mid = ((r >> 32) & 0xffff_ffff) as u32;
    ((r >> 64) as u64, mid)
}

/// For any p in `POWERSOF10_FIRST..=POWERSOF10_LAST`, return the most
/// significant 64 bits of `pow(10,p)` (shifted to fill the u64), plus the
/// next 32 significant bits in `lo`. (`sqlite3_powerOfTen`.)
fn power_of_ten(p: i32) -> (u64, u32) {
    debug_assert!((POWERSOF10_FIRST..=POWERSOF10_LAST).contains(&p));
    let (g, n): (i32, i32);
    if p < 0 {
        if p == -1 {
            return (A_SCALE[13], A_SCALE_LO[13]);
        }
        // C integer division truncates toward zero — Rust matches.
        g = p / 27;
        n = p % 27;
        // (g, n) mutated together below via temporaries.
        let (mut g2, mut n2) = (g, n);
        if n2 != 0 {
            g2 -= 1;
            n2 += 27;
        }
        return power_of_ten_scaled(g2, n2);
    } else if p < 27 {
        return (A_BASE[p as usize], 0);
    } else {
        g = p / 27;
        n = p % 27;
    }
    power_of_ten_scaled(g, n)
}

/// The aScale/aBase composition path shared by both sign branches.
fn power_of_ten_scaled(g: i32, n: i32) -> (u64, u32) {
    let idx = (g + 13) as usize;
    let s = A_SCALE[idx];
    let s_lo = A_SCALE_LO[idx];
    if n == 0 {
        return (s, s_lo);
    }
    let (mut x, mut lo) = mul160(s, s_lo, A_BASE[n as usize]);
    if (u64_bit(63) & x) == 0 {
        x = (x << 1) | u64::from((lo >> 31) & 1);
        lo = (lo << 1) | 1;
    }
    (x, lo)
}

/// Given `m` and `e` representing `r == m * 2^e` (m normalized with its
/// highest bit set), return `(d, p)` such that `r ≈ d * 10^p` with `d`
/// carrying `n` significant digits (rounded). (`sqlite3Fp2Convert10`.)
fn fp2_convert10(m: u64, e: i32, n: i32) -> (u64, i32) {
    debug_assert!((1..=18).contains(&n));
    let p = n - 1 - pwr2to10(e + 63);
    let (pw_hi, _pw_lo_unused) = power_of_ten(p);
    let (hi, _lo) = mul128(m, pw_hi);
    let d = if n == 18 {
        let h = hi >> -(e + pwr10to2(p) + 2);
        (h.wrapping_add((h << 1) & 2)) >> 1
    } else {
        hi >> -(e + pwr10to2(p) + 1)
    };
    (d, -p)
}

/// Return the IEEE754 double that best approximates `d * 10^p`.
/// (Adapted from the work of Russ Cox — `sqlite3Fp10Convert2`.)
fn fp10_convert2(d: u64, p: i32) -> f64 {
    if p < POWERSOF10_FIRST {
        return 0.0;
    }
    if p > POWERSOF10_LAST {
        return f64::INFINITY;
    }
    let b = (64 - d.leading_zeros()) as i32;
    let lp = pwr10to2(p);
    let mut e = 53 - b - lp;
    if e > 1074 {
        if e >= 1130 {
            return 0.0;
        }
        e = 1074;
    }
    let s = -(e - (64 - b) + lp + 3);
    let (mut pwr10h, mut pwr10l) = power_of_ten(p);
    if pwr10l != 0 {
        pwr10h = pwr10h.wrapping_add(1);
        pwr10l = !pwr10l;
    }
    let x = d << (64 - b) as u32;
    let (mut hi, lo) = mul128(x, pwr10h);
    let mid1 = (lo >> 32) as u32;
    let mut sticky: u64 = 1;
    let mask_low: u64 = if s >= 64 {
        u64::MAX
    } else {
        u64_bit(s as u32).wrapping_sub(1)
    };
    if (hi & mask_low) == 0 {
        // hi's low s bits are zero — refine with the next 32 bits to
        // decide stickiness exactly as SQLite does. (Multiply128 returns
        // the HIGH half; mid2 is its top 32 bits.)
        let (hi2, _lo2) = mul128(x, (pwr10l as u64) << 32);
        let mid2 = (hi2 >> 32) as u32;
        sticky = u64::from(mid1.wrapping_sub(mid2) > 1);
        if mid1 < mid2 {
            hi = hi.wrapping_sub(1);
        }
    }
    let mut u = if s >= 64 {
        sticky // hi >> 64 == 0
    } else {
        (hi >> s as u32) | sticky
    };
    let adj: i32 = i32::from(u >= u64_bit(55).wrapping_sub(2));
    if adj != 0 {
        u = (u >> adj as u32) | (u & 1);
        e -= adj;
    }
    let m = (u.wrapping_add(1).wrapping_add((u >> 2) & 1)) >> 2;
    if e <= -972 {
        return f64::INFINITY;
    }
    let mut m = m;
    if (m & u64_bit(52)) != 0 {
        m = (m & !u64_bit(52)) | (((1075 - e) as u64) << 52);
    }
    f64::from_bits(m)
}

/// The decoded form of a double: sign, significant digits (ASCII), the
/// digit count `n`, and the decimal-point position `i_dp` (digits before
/// the point = `i_dp`; `i_dp <= 0` means `0.` followed by zeros).
pub struct FpDecode {
    /// '+' or '-'.
    pub sign: u8,
    /// Digit bytes; the ACTIVE digits are `z[zi..zi+n]` (the carry path
    /// can move the start left within the buffer).
    pub z: [u8; 24],
    pub zi: usize,
    pub n: usize,
    pub i_dp: i32,
}

impl FpDecode {
    /// The active digit slice.
    #[inline]
    pub fn digits(&self) -> &[u8] {
        &self.z[self.zi..self.zi + self.n]
    }
}

/// Decode `r` into up to `i_round` significant digits (0 = "as many as
/// needed"), never more than `mx_round`, with SQLite's exact rounding and
/// (at `i_round == 17`) the round-trip digit-count reduction.
/// (`sqlite3FpDecode`.)
pub fn fp_decode(r: f64, i_round: i32, mx_round: i32) -> FpDecode {
    debug_assert!(mx_round > 0);
    if r < 0.0 {
        let mut d = fp_decode_pos(-r, i_round, mx_round);
        d.sign = b'-';
        return d;
    }
    if r == 0.0 {
        // Both +0.0 and -0.0 handled: SQLite prints "0.0" for -0.0 (the
        // r<0.0 test is FALSE for -0.0 in IEEE, so the sign never flips).
        let mut z = [0u8; 24];
        z[23] = b'0';
        return FpDecode {
            sign: b'+',
            z,
            zi: 23,
            n: 1,
            i_dp: 1,
        };
    }
    fp_decode_pos(r, i_round, mx_round)
}

fn fp_decode_pos(r: f64, i_round: i32, mx_round: i32) -> FpDecode {
    // Special exponents (inf/nan) are handled by the renderer; mirror
    // SQLite's isSpecial early return (empty digits).
    let bits = r.to_bits();
    let biased = ((bits >> 52) & 0x7ff) as i32;
    if biased == 0x7ff {
        return FpDecode {
            sign: b'+',
            z: [0u8; 24],
            zi: 24,
            n: 0,
            i_dp: 0,
        };
    }
    let mut v = bits & 0x000f_ffff_ffff_ffff;
    let e_biased;
    if biased == 0 {
        let nn = v.leading_zeros() as i32;
        v <<= nn;
        e_biased = -1074 - nn;
    } else {
        v = (v << 11) | u64_bit(63);
        e_biased = biased - 1086;
    }
    let m = v; // significand with the top bit set
    let e = e_biased; // r == m * 2^e

    let n_digits = if i_round <= 0 || i_round >= 18 {
        18
    } else {
        i_round + 1
    };
    let (v10, exp) = fp2_convert10(m, e, n_digits);

    // Extract significant digits right-aligned in the buffer.
    let mut z = [0u8; 24];
    let mut i = 24usize;
    let mut vv = v10;
    while vv >= 10 {
        let pair = (vv % 100) as usize;
        z[i - 2] = b'0' + (pair / 10) as u8;
        z[i - 1] = b'0' + (pair % 10) as u8;
        i -= 2;
        vv /= 100;
    }
    if vv > 0 {
        i -= 1;
        z[i] = b'0' + vv as u8;
    }
    let mut n = 24 - i; // total digits extracted
    let mut i_dp = n as i32 + exp;
    let mut i_round = i_round;
    if i_round <= 0 {
        i_round = i_dp - i_round;
        if i_round == 0 && z[i] >= b'5' {
            i_round = 1;
            i -= 1;
            z[i] = b'0';
            n += 1;
            i_dp += 1;
        }
    }
    let mut zi = i;
    if i_round > 0 && ((i_round as usize) < n || n > mx_round as usize) {
        let mut ir = i_round;
        if ir > mx_round {
            ir = mx_round;
        }
        let d = &z[zi..];
        if ir == 17 {
            // The "!"-flag reduction: shrink the digit count when the
            // shorter value round-trips to the same double.
            if d[15] == b'9' && d[14] == b'9' {
                let mut jj = 14usize;
                while jj > 0 && d[jj - 1] == b'9' {
                    jj -= 1;
                }
                let v2 = if jj == 0 {
                    1u64
                } else {
                    let mut t = u64::from(d[0] - b'0');
                    for digit in d[1..jj].iter() {
                        t = t.wrapping_mul(10).wrapping_add(u64::from(*digit - b'0'));
                    }
                    t.wrapping_add(1)
                };
                if r == fp10_convert2(v2, exp + n as i32 - jj as i32) {
                    ir = jj as i32 + 1;
                }
            } else if i_dp >= n as i32 || (d[15] == b'0' && d[14] == b'0' && d[13] == b'0') {
                debug_assert!(d[0] != b'0');
                let mut jj = 13usize;
                while d[jj - 1] == b'0' {
                    jj -= 1;
                }
                let mut v2 = u64::from(d[0] - b'0');
                for digit in d[1..jj].iter() {
                    v2 = v2.wrapping_mul(10).wrapping_add(u64::from(*digit - b'0'));
                }
                if r == fp10_convert2(v2, exp + n as i32 - jj as i32) {
                    ir = jj as i32 + 1;
                }
            }
        }
        n = ir as usize;
        if z[zi + n] >= b'5' {
            // Round up with carry; the carry can prepend a '1' digit
            // (the C walks j relative to the digit START — `j==0` means
            // the first digit, not buffer index zero).
            let mut j = zi + n - 1;
            loop {
                z[j] += 1;
                if z[j] <= b'9' {
                    break;
                }
                z[j] = b'0';
                if j == zi {
                    zi -= 1;
                    z[zi] = b'1';
                    n += 1;
                    i_dp += 1;
                    break;
                }
                j -= 1;
            }
        }
    }
    let _ = i;
    FpDecode {
        sign: b'+',
        z,
        zi,
        n,
        i_dp,
    }
}

/// Render an f64 exactly like SQLite 3.53+'s REAL→TEXT: the `%!.17g`
/// etGENERIC assembly (17 significant digits, scientific when
/// `exp < -4 || exp > 16`, trailing zeros stripped, a guaranteed decimal
/// point, exponent always sign + two-or-three digits).
///
/// * `0.0` / `-0.0` → `"0.0"`
/// * `±inf` → `"Inf"` / `"-Inf"` (SQL REAL→TEXT; JSON's zeropad variant
///   renders `9.0e+999` — see the jsonb renderer)
/// * NaN → `"NaN"` (printf's no-zeropad spelling)
pub fn render_real_353(v: f64) -> String {
    if v.is_nan() {
        return "NaN".to_string();
    }
    if v.is_infinite() {
        return if v > 0.0 { "Inf" } else { "-Inf" }.to_string();
    }
    let d = fp_decode(v, 17, 20);
    let mut out = String::with_capacity(24);
    if d.sign == b'-' {
        out.push('-');
    }
    let digits = d.digits();
    let n = digits.len();
    let exp = d.i_dp - 1;
    // etGENERIC at precision 17: precision-- → 16; scientific when
    // exp < -4 or exp > 16; fixed precision = 16 - exp otherwise.
    let sci = !(-4..=16).contains(&exp);
    let mut j = 0usize;
    let mut precision: i32 = if sci { 16 } else { 16 - exp };
    if !sci {
        let mut e2 = d.i_dp - 1;
        if e2 < 0 {
            out.push('0');
        } else {
            while e2 >= 0 {
                out.push(if j < n { digits[j] as char } else { '0' });
                j += 1;
                e2 -= 1;
            }
        }
        out.push('.');
        e2 += 1;
        while e2 < 0 && precision > 0 {
            out.push('0');
            precision -= 1;
            e2 += 1;
        }
    } else {
        out.push(if j < n { digits[j] as char } else { '0' });
        j += 1;
        out.push('.');
    }
    while precision > 0 {
        precision -= 1;
        out.push(if j < n { digits[j] as char } else { '0' });
        j += 1;
    }
    // Trailing-zero strip; keep a final ".0".
    while out.ends_with('0') {
        out.pop();
    }
    if out.ends_with('.') {
        out.push('0');
    }
    if sci {
        let mut e = exp;
        out.push('e');
        if e < 0 {
            out.push('-');
            e = -e;
        } else {
            out.push('+');
        }
        if e >= 100 {
            out.push((b'0' + (e / 100) as u8) as char);
            e %= 100;
        }
        out.push((b'0' + (e / 10) as u8) as char);
        out.push((b'0' + (e % 10) as u8) as char);
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Golden values generated by the REAL 3.53.4 amalgamation
    /// (vdbeMemRenderNum / "%!.*g" with nFpDigit=17).
    #[test]
    fn golden_353_renders() {
        let cases: &[(f64, &str)] = &[
            (0.0, "0.0"),
            (-0.0, "0.0"),
            (1.0, "1.0"),
            (0.1, "0.1"),
            (0.5, "0.5"),
            (1.5, "1.5"),
            (2.0 / 3.0, "0.66666666666666663"),
            (0.1 + 0.2, "0.30000000000000004"),
            (1e15, "1000000000000000.0"),
            (1e16, "10000000000000000.0"),
            (1e17, "1.0e+17"),
            (1e18, "1.0e+18"),
            (1e300, "1.0e+300"),
            (0.0001, "0.0001"),
            (0.00001, "1.0e-05"),
            (1.5e-5, "1.5e-05"),
            (4.9e-324, "4.9406564584124654e-324"),
            (1.7976931348623157e308, "1.7976931348623157e+308"),
            (123456789012345678.0, "1.2345678901234568e+17"),
            (49.47, "49.47"),
            (-49.47, "-49.47"),
            (f64::INFINITY, "Inf"),
            (f64::NEG_INFINITY, "-Inf"),
        ];
        for (v, want) in cases {
            assert_eq!(&render_real_353(*v), want, "render({:?})", v);
        }
    }
}
